--- 
- 
  become: true
  become_method: sudo
  gather_facts: false
  hosts: 
    - all
  tasks: 
    - 
      command: "apt update"
      name: "Update repos"
    - 
      apt: 
        name: 
          - apt-transport-https
          - gnupg
          - ca-certificates
          - curl
          - software-properties-common
      name: "Install prerequisites for Docker repository"
    - 
      apt_key: 
        url: "https://download.docker.com/linux/ubuntu/gpg"
      name: "Add Docker GPG key"
    - 
      apt_repository: 
        repo: "deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
      name: "Add Docker APT repository"
    - 
      apt: 
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: true
      name: "Install Docker CE"
    - 
      command: "groupadd docker && usermod -aG docker $USER && newgrp docker && service docker start"
      name: "add user and start docker"
